let alerta=alert(`SI ENVÍAS TUS INFORMACIÓN ACEPTA QUE EVIEMOS MENSAJE A
Su GMAIL SUS DATOS VAN  HACER USADO CON DISCRECIÓN
Y SIN PROPÓSITO DAÑINO SOLO Y ÚNICAMENTE SE VAN A USAR PARA MANDAR INFORMACIÓN A USTE.`);
